### ISSUE TITLE
(RtMidi) The specified module could not be found

### ISSUE THREAD

**Issue by gh-jsoares** [atsushieno/ktmidi#19]
Hello,

I was testing the library to see if I could use it on my system. For some reason, when I try to get MIDI access, java cannot load the rtmidi module. I'm using gradle version `7.2`; kotlin version `1.6.10`; java compile target `1.8`; and the jvm is temurin `17.0.1`.

This is the stack trace:
```gradle
Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found.
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at dev.atsushieno.rtmidijna.RtmidiLibrary.<clinit>(RtmidiLibrary.java:20)
	at dev.atsushieno.ktmidi.RtMidiAccess.<clinit>(RtMidiAccess.kt:12)
	at MainKt.main(Main.kt:6)
```

This is the code:
```kotlin
import dev.atsushieno.ktmidi.AlsaMidiAccess
import dev.atsushieno.ktmidi.RtMidiAccess
import java.io.File

fun main(args: Array<String>) {
    val access = if(File("/dev/snd/seq").exists()) AlsaMidiAccess() else RtMidiAccess()
    access.inputs.forEach {
        println("${it.id} ${it.name} [ ${it.manufacturer} ] - ver. ${it.version}")
    }
}
```

This is the gradle implementation block:
```gradle
val ktmidi_version = "0.3.16"
dependencies {
    implementation("dev.atsushieno:ktmidi:$ktmidi_version")
    implementation("dev.atsushieno:ktmidi-jvm:$ktmidi_version")
    implementation("dev.atsushieno:ktmidi-jvm-desktop:$ktmidi_version")
}
```

Checking the external libraries, I can see that gradle did in fact pull 5 dependencies with your package name. Here is a screenshot (I expanded the rtmidi-jna block to verify that the dll files were included):
![External Libraries](https://files.perpheads.com/aB8aPnXPT4QOQznX.png)

I'm unsure as to why this is happening as this is a bit beyond my knowledge at this point.

Thanks in advance!

**Comment by atsushieno** [comment]
I don't have any project that specifies your versions of the deps (my apps use Jetpack Compose which cannot upgrade to Kotlin 1.6.10). Besides I have no idea which platform your are running your app - I only use Linux desktop on my daily basis so other platforms are not really tested. I verified my [atsushieno/kmmk](https://github.com/atsushieno/kmmk/) on Mac now and it seems to work. It does not have any trick to specify library paths.

For rtmidi-jna, the native library paths are not resolved by myself but it is completely handled by JNA, JNAerator, and gradle-jnaerator-plugin, if involved. Therefore I myself don't have a lot of ideas either - the rtmidi-jna jar is built on [atsushieno/rtmidi-jna](https://github.com/atsushieno/rtmidi-jna) [GitHub Actions setup](https://github.com/atsushieno/rtmidi-jna/blob/main/.github/workflows/actions_package_reg.yml) which first builds Win64/Mac Darwin64 / Linux64 native libs respectively and collect into one jar build. If your platform is something else (for example, ARM CPUs, 32-bit Windows, or 32-bit Linux), you will have to provide (lib)rtmidi by your own. (I assume it works if it is on LD_LIBRARY_PATH or equivalents, but not completely sure.)

The native library paths are specified at its [build.gradle](https://github.com/atsushieno/rtmidi-jna/blob/1c9ed5287121070a428cb0ff31cb40d19a6da0d9/rtmidi-jna/build.gradle#L46) in the `jnaerator` section used by [gradle-jnaerator-plugin](https://github.com/atsushieno/gradle-jnaerator-plugin), and... the paths specified there do not match whatever the resulting jar contains. That is, it is gradle-jnaereator-plugin which places those files at those paths, and it is presumably right for usual jar consumption.

**Comment by gh-jsoares** [comment]
After a lot of tinkering, I decided to compile my own version of rtmidi's library and use it with your wrapper. It did not work at first and kept throwing quite a few weird errors. This is my first time experimenting with native access and dynamic libraries so I am way out of my depth.

When I finally got it to load the library properly, some function calls were resulting in _"Illegal Memory Access"_ errors. After some research I found out that this can be due to not memory not being allocated in the dynamic library and then the java code is attempting to use it. Regardless, this made me check the source code of rtmidi that I had previously downloaded and compiled. The function had different signature from the Java library class. From this, I concluded you were using a different version in your **rtmidi-jna** package and after compiling the same commit as you, it finally worked!

With this, the issue I had initially was solved by recompiling the dll files.

**Comment by atsushieno** [comment]
Ahh, that's a good call. It seems that rtmidi does not respect backward ABI compatibility (C++ is a statically compiled and linked language so it often happens that they only respect API compatibility).

I will update README to add a link to rtmidi-jna, and mention any possible ABI issues on its README there. Once I'm done with it I will close this issue. Thanks for sharing the experience!
