### ISSUE TITLE
JvmMidiAccess does not recognize input ports

### ISSUE THREAD

**Issue by Burtan** [atsushieno/ktmidi#27]
Hey,
thanks for creating this library.

However, JvmMidiAccess does not find any of my midi input ports. A quick look into the sources showed that it maps all receivers, but they are all empty in my case. Would you accept pull requests on a fix for this?

**Comment by atsushieno** [comment]
Hey, thanks for the report. Sure I welcome PR and accept it if it looks good :-)

**Comment by Burtan** [comment]
Do you plan to release a new version with this?

**Comment by atsushieno** [comment]
Oh, sure I will publish a new version for you. But probably after we sort out what to do for #29? (It is not mandatory, if it's going to take longer time.)

**Comment by Burtan** [comment]
I think #29 will take a little longer, but I'll get to it in some weeks I think. So an intermediate release would be nice :-).

**Comment by atsushieno** [comment]
done!
