### ISSUE TITLE
Use data classes when possible

### ISSUE THREAD

**Issue by Burtan** [atsushieno/ktmidi#31]
I think data classes are a good fit for midi event associated classes. It's perfect to carry immutable data.

**Comment by atsushieno** [comment]
`MidiEvent` is not that simple as it has many constructors. Since it has to support simple MIDI events as well as SysEx events, it is complicated by nature.

On the other hand, `Ump` is simple, and it's already a data class.

**Comment by atsushieno** [comment]
Closing as per discussed (more) at #34.
