### ISSUE TITLE
local rtmidi setup instruction

### ISSUE THREAD

**Issue by sed0** [atsushieno/ktmidi#35]
I tried using ktmidi for jvm-desktop and got UnsatisfiedLinkError. Tried to debug and putting a renamed rtmidi.dll to C:\Users\%user%\AppData\Local\Temp\jna-72501012\ (found this directory while debugging, it tries to open a .dll with randomly generated name and fails, I thought replacing it might help) but I still got the exception. Not sure what I have to do and what I've been doing wrong, an instruction would help

**Comment by atsushieno** [comment]
I hope to have any better solution, but unfortunately didn't really have any luck.

So far README https://github.com/atsushieno/ktmidi#platform-access-api mentions that you are supposed to have rtmidi(.dll) on one of your platform paths.

**Comment by sed0** [comment]
I imported the library to my main project and had to raise java version, everything works now after I included it as a normal dependency. Thank you!
