### ISSUE TITLE
android inputs and outputs are not updated on MidiAccess.inputs/otuputs call

### ISSUE THREAD

**Issue by sed0** [atsushieno/ktmidi#38]
The ports variable is not updated upon access and doesn't allow to get updated inputs/outputs lists. Might be solved by adding get() to it. Adding a listener or flows will solve this too.

**Comment by atsushieno** [comment]
Thanks for reporting it. Yeah making it to get() would certainly makes listing live.
Using `MidiManager.DeviceCallback` would be safer as we would probably like to keep `AndroidPort` instances not potentially outdated, but probably having more than one `AndroidPort`s to the actual port instance in Android MIDI API would be harmless.

**Comment by atsushieno** [comment]
I will work on it and publish the next release next week (should be trivial but busy until Sunday).

**Comment by atsushieno** [comment]
I'm not fully back on track yet privately, and apart from that I've been stuck at various Android Studio issues that prevent launching my dev. emulator on Linux (and Mac not usable for that arm64 issue). There isn't a project that can verify the fix, so there is only unverified code changes at hand now.

**Comment by atsushieno** [comment]
`ports` is now a simple and stupid getter. It still does not use `MidiManager.DeviceCallback` this time. Device change detection events will be appropriately implemented (at #43). Thanks for the report and suggestion for the fix!
