### ISSUE TITLE
lower android minSdk to 23

### ISSUE THREAD

**Issue by sed0** [atsushieno/ktmidi#42]
I was unable to find anything that can't work on 23, am I missing something?

**Comment by atsushieno** [comment]
In theory it would work on API Level 23, though  I set it to 24 by intention.

I find API Level 24 for most comfortable to support any Java stuff that had migrated to OpenJDK and namely Java8 language and its base library API. If we lower the minSdk to 23 and keep it as the expected lowest version, we will be unable to write any code that depends on Java8 features. That's what I would like to avoid.

Having said that, shipping ktmidi that "once supported" minSdk = 23 is not a bad idea. We can keep it until we want to write any code that depends on Java8. Let me state that I have no hesitate to discard that at any time...!

**Comment by atsushieno** [comment]
Apart from that, is your suggestion for any practical reason, or just like "it can be lower" ?

**Comment by sed0** [comment]
> Apart from that, is your suggestion for any practical reason, or just like "it can be lower" ?

It's just to support more devices. I don't see any Java8 features that can be used in this library (but that's just me!), and also some of the Java8 features are available without a higher sdk level. I'm not pushing it though, just wanted to know if there's a reason for a higher sdk level!

**Comment by atsushieno** [comment]
Let's roll 0.4.2 release so that anyone who wants to support Android 6.0  in their app builds upon ktmidi can survive...!
