### ISSUE TITLE
All device IDs are 0 in TraditionalCoreMidiAccess

### ISSUE THREAD

**Issue by JBramEu** [atsushieno/ktmidi#86]
**ISSUE**: The ids of all midi devices (both, inputs and outputs) are `0` (TraditionalCoreMidiAccess), so we cannot distinguish them by id, even though those fields should be unique according to apple docs.

This is the definition of the field in CoreMidiPortDetails
```
    @OptIn(ExperimentalForeignApi::class)
    override val id: String
        get() = getPropertyInt(endpoint, kMIDIPropertyUniqueID).toString()
```

And here's the Apple docs for the field:
https://developer.apple.com/documentation/coremidi/kmidipropertyuniqueid

UPDATE: Tested and reproduced by connecting 3 USB MIDI devices (via a powered hub) and one MIDI network session to a non-M1 iPad Pro with iPadOS 17.5.1. Same result (id 0) is also present when connecting one USB device directly to the iPad (plus the network session, also id 0).

_Originally posted by @JBramEu in https://github.com/atsushieno/ktmidi/issues/85#issuecomment-2271503687_

**Comment by JBramEu** [comment]
The fault is in `getPropertyInt`, which always returns 0.
This also effects all other uses of the function, e.g. `CoreMidiPortDetails.midiTransportProtocol`

Here's the fixed function:
```
@OptIn(ExperimentalForeignApi::class)
internal fun getPropertyInt(obj: MIDIObjectRef, property: CFStringRef?): Int {
    memScoped {
        val i = alloc<SInt32Var>()
        checkStatus { MIDIObjectGetIntegerProperty(obj, property, i.ptr) }
        return i.value
    }
}
```

**Comment by atsushieno** [comment]
Applied this too. Thanks!
